### ISSUE TITLE
question preparation

### ISSUE THREAD

**Issue by Norooa** [ZHU-Zhiyu/High-Rank_RGB-Event_Tracker#1]
Thank you for sharing the code. But I have a few question of the preparation to run the code in the readme document.
First, I didn't find the code to convert the data, how can I get it ?
![image](https://github.com/ZHU-Zhiyu/High-Rank_RGB-Event_Tracker/assets/52622427/62215d6c-02e9-4252-b3a7-5f81a3ab5871)
second, is the means I should download the pretrained model of Swin2 and put it into the folder? But the link you give seems can't download the model.(of course I can find the model by myself, but it seems a little question in your document)
![image](https://github.com/ZHU-Zhiyu/High-Rank_RGB-Event_Tracker/assets/52622427/72c78fe2-a790-4c9f-b163-5c793ecf8b20)
If you can answer my question I will be very grateful.

**Comment by ZHU-Zhiyu** [comment]
Hi @Norooa . Thanks for your interests. We have uploaded corresponding links and files. Please remeber to set the path in Evt_convert.py. If any question, feel free to ask.

**Comment by ZHU-Zhiyu** [comment]
Hi @Norooa. If no more question, I'll close the issue. Thanks.
