### ISSUE TITLE
Data Preparation

### ISSUE THREAD

**Issue by JadeCityYC** [ZHU-Zhiyu/High-Rank_RGB-Event_Tracker#2]
Hi, just want to know where is the data.py file to transfer and clip COESOT dataset to mat files.

python ./COESOT/data.py

It would be grateful if you could answer it.

**Comment by ZHU-Zhiyu** [comment]
Hi @chenyucheng0221 , I'm sorry for the confusion. To convert COESOT, you can run the ./HRCEUTrack/Base/scripts/event_to_voxel_coesot.py, just like the original COESOT dataset. If any question feel free to contact me. I'll correct it soon.

**Comment by ZHU-Zhiyu** [comment]
@chenyucheng0221 please remmeber to set correct path

**Comment by JadeCityYC** [comment]
Thank you for answering!

**Comment by JadeCityYC** [comment]
Hi, I tried to run ./HRCEUTrack/Base/scripts/event_to_voxel_coesot.py as you said, and the path has been set correctly. However, I get this error:

`$ python event_to_voxel_coesot.py`

`==>> foldName:  dvSave-2021_12_21_12_10_11
Traceback (most recent call last):
  File "event_to_voxel_coesot.py", line 91, in <module>
    os.mkdir(os.path.join(save_path, foldName, foldName+'_voxel'))
FileNotFoundError: [Errno 2] No such file or directory: '/mnt/dev-ssd-8T/yuchengchen/Dataset/COESOT/training_voxel/dvSave-2021_12_21_12_10_11/dvSave-2021_12_21_12_10_11_voxel`


Have you hit this issue?

Thanks

**Comment by ZHU-Zhiyu** [comment]
@chenyucheng0221 Hi, can you check that is this directory ("/mnt/dev-ssd-8T/yuchengchen/Dataset/COESOT/training_voxel/dvSave-2021_12_21_12_10_11/") existed? This error usually occurs that you are creating two or even more levels directories.

**Comment by ZHU-Zhiyu** [comment]
Hi @chenyucheng0221 I'll close the issue, if no more questions. Thanks.
