### ISSUE TITLE
h5 files

### ISSUE THREAD

**Issue by Silvia-song** [ZHU-Zhiyu/High-Rank_RGB-Event_Tracker#6]
Hi! Thank you for providing the code. I have a question regarding the generation of h5 files. I have set the path in Evt_convert.py, but after running the code, the h5 files were not generated. Additionally, I noticed that `save_file` is used to specify the path to save the h5 file, but this variable is not utilized in the subsequent code. I would greatly appreciate it if you could reply to my questions.
<img width="580" alt="save_file" src="https://github.com/user-attachments/assets/b14bc381-656f-4730-b6a7-f9e288a3bdb5">

**Comment by ZHU-Zhiyu** [comment]
Hi @Silvia-song I have corrected the code. You can give it a try. Moreover, COESOT is a more comprehensive benchmark to evaluate your trackers, based on my experimental experience.

**Comment by Silvia-song** [comment]
Thank you for the update. I have successfully resolved my issue. Furthermore, I will explore COESOT as your recommendation. Thank you for your guidance.
